"""
Pipeline for generating Docusaurus sidebar configuration.
"""
import json
import os
from pathlib import Path

def generate_sidebar():
    """
    Task 4.1 — Generate_Sidebar
    Create Docusaurus sidebar configuration that matches the book outline structure
    """
    # Load the outline to generate the sidebar
    outline_path = "backend/pipelines/outline.json"
    if not os.path.exists(outline_path):
        print(f"Warning: {outline_path} not found, using template")
        # Create a template outline if it doesn't exist
        from .pdf_extraction import build_outline
        outline = build_outline(
            "backend/processing/themes.json",
            "backend/processing/modules.json",
            "backend/processing/weeks.json"
        )
    else:
        with open(outline_path, 'r') as f:
            outline = json.load(f)

    # Generate sidebar structure
    sidebar = {
        "textbook": [
            {
                "type": "autogenerated",
                "dirName": "."
            }
        ]
    }

    # Create a more specific sidebar based on the outline
    sidebar = {
        "textbook": []
    }

    for part in outline['parts']:
        part_entry = {
            "type": "category",
            "label": f"Part {part['part_number']}: {part['title']}",
            "items": []
        }

        for chapter in part['chapters']:
            # Convert chapter title to the expected file name format
            # Replace spaces with underscores and make lowercase
            file_name = chapter['id']
            part_entry["items"].append(f"part_{part['part_number'].lower()}/{file_name}")

        sidebar["textbook"].append(part_entry)

    # Ensure the docusaurus directory exists
    sidebar_dir = Path("frontend/docusaurus")
    sidebar_dir.mkdir(parents=True, exist_ok=True)

    # Write the sidebar configuration
    sidebar_path = sidebar_dir / "sidebars.js"
    with open(sidebar_path, 'w') as f:
        f.write("module.exports = ")
        json.dump(sidebar, f, indent=2)
        f.write(";\n")

    print(f"Sidebar generated at {sidebar_path}")
    return sidebar_path